.gitmodules
ImperatorToCk3.sln.DotSettings
ImperatorToCk3/Copy_Files.bat
ImperatorToCk3/Data_Files/configuration_l_english.yml
ImperatorToCk3/Data_Files/fronter-configuration.txt
ImperatorToCk3/Data_Files/fronter-options.txt
ImperatorToCk3/Data_Files/options_l_english.yml
ImperatorToCk3/ImperatorToCk3.vcxproj
ImperatorToCk3/ImperatorToCk3.vcxproj.filters
ImperatorToCk3/Source/Configuration/Configuration.cpp
ImperatorToCk3/Source/Imperator/Characters/Character.cpp
ImperatorToCk3/Source/Imperator/Characters/Character.h
ImperatorToCk3/Source/Imperator/Characters/CharacterAttributes.cpp
ImperatorToCk3/Source/Imperator/Characters/CharacterAttributes.h
ImperatorToCk3/Source/Imperator/Characters/CharacterName.cpp
ImperatorToCk3/Source/Imperator/Characters/CharacterName.h
ImperatorToCk3/Source/Imperator/Characters/Characters.cpp
ImperatorToCk3/Source/Imperator/Characters/Characters.h
ImperatorToCk3/Source/Imperator/Families/Families.cpp
ImperatorToCk3/Source/Imperator/Families/Families.h
ImperatorToCk3/Source/Imperator/ImperatorWorld.cpp
ImperatorToCk3/Source/Imperator/ImperatorWorld.h
ImperatorToCk3Tests/ImperatorToCK3Tests.vcxproj
ImperatorToCk3Tests/ImperatorToCK3Tests.vcxproj.filters
ImperatorToCk3Tests/ImperatorWorldTests/Characters/CharacterTests.cpp
ImperatorToCk3Tests/ImperatorWorldTests/Characters/CharactersTests.cpp

- Updated submodules
- Added a FamiliesBloc class
- Reading characters

Reading Families and Characters

---

ImperatorToCK3/Data_Files/configurables/province_mappings.txt
ImperatorToCK3/ImperatorToCK3.vcxproj
ImperatorToCK3/ImperatorToCK3.vcxproj.filters
ImperatorToCK3/Source/Mappers/ProvinceMapper/ProvinceMapper.cpp
ImperatorToCK3/Source/Mappers/ProvinceMapper/ProvinceMapper.h
ImperatorToCK3/Source/Mappers/ProvinceMapper/ProvinceMapping.cpp
ImperatorToCK3/Source/Mappers/ProvinceMapper/ProvinceMapping.h
ImperatorToCK3/Source/Mappers/ProvinceMapper/ProvinceMappingsVersion.cpp
ImperatorToCK3/Source/Mappers/ProvinceMapper/ProvinceMappingsVersion.h
ImperatorToCK3Tests/ImperatorToCK3Tests.vcxproj
ImperatorToCK3Tests/ImperatorToCK3Tests.vcxproj.filters
ImperatorToCk3Tests/MapperTests/ProvinceMapper/ProvinceMapperTests.cpp
ImperatorToCk3Tests/MapperTests/ProvinceMapper/ProvinceMappingTests.cpp
ImperatorToCk3Tests/MapperTests/ProvinceMapper/ProvinceMappingsVersionTests.cpp

- ProvinceMapper
- Province mappings in the British Isles

First province mappings

---

ImperatorToCK3/Data_Files/configurables/province_mappings.txt

- Scandinavia
- Iberian Peninsula
- Morocco
- Algeria

More province mappings

---

ImperatorToCK3/Data_Files/configurables/province_mappings.txt
ImperatorToCK3/Data_Files/fronter-configuration.txt
ImperatorToCK3/Source/Configuration/Configuration.cpp
ImperatorToCK3/Source/Configuration/Configuration.h

Also added some province mappings in Arabia

Enabled verifyCK3Path, added CK3ModsPath

---

.github/workflows/codeql-analysis.yml
ImperatorToCK3/Copy_Files_Release.bat
ImperatorToCK3/Data_Files/ReadMe.txt
ImperatorToCK3/Data_Files/blankMod/dummy.txt
ImperatorToCK3/Data_Files/blankMod/output/common/religion/religions/00_kushitism.txt
ImperatorToCK3/Data_Files/blankMod/output/common/religion/religions/anatolian_pagan.txt
ImperatorToCK3/Data_Files/blankMod/output/common/religion/religions/arabic_pagan.txt
ImperatorToCK3/Data_Files/blankMod/output/common/religion/religions/armenian_pagan.txt
ImperatorToCK3/Data_Files/blankMod/output/common/religion/religions/berber_pagan.txt
ImperatorToCK3/Data_Files/blankMod/output/common/religion/religions/canaanite_pagan.txt
ImperatorToCK3/Data_Files/blankMod/output/common/religion/religions/caucasian_pagan.txt
ImperatorToCK3/Data_Files/blankMod/output/common/religion/religions/celtic_pagan.txt
ImperatorToCK3/Data_Files/blankMod/output/common/religion/religions/dacian_pagan.txt
ImperatorToCK3/Data_Files/blankMod/output/common/religion/religions/iberic_pagan.txt
ImperatorToCK3/Data_Files/blankMod/output/common/religion/religions/mesopotamian_pagan.txt
ImperatorToCK3/Data_Files/blankMod/output/common/religion/religions/scythian_pagan.txt
ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_pagan_religion_l_english.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/french/CONVERTER_pagan_religion_l_french.yml
ImperatorToCK3/Data_Files/configurables/religion_map.txt
ImperatorToCK3/ImperatorToCK3.vcxproj
ImperatorToCK3/Source/CK3Outputter/CK3WorldOutputter.cpp

Credits to lukaslunt for the files.

Religion files

---

ImperatorToCK3.sln.DotSettings
ImperatorToCK3/Data_Files/fronter-configuration.txt
ImperatorToCK3/Source/CK3/CK3World.cpp
ImperatorToCK3/Source/CK3/CK3World.h
ImperatorToCK3/Source/CK3/Titles/TitlesHistory.cpp
ImperatorToCK3/Source/CK3/Titles/TitlesHistory.h

- Remove invalid landless titles
- Mod copying fix

Title history removal fix

---

ImperatorToCK3/Source/Mappers/LocalizationMapper/LocalizationMapper.cpp

Check string length before accessing a character at a position.
@Zemurin CK3ToEU4 probably needs this fix too.

LocalizationMapper fix

---

ImperatorToCK3/Data_Files/blankMod/output/common/customizable_localization/00_ES_custom_loc.txt
ImperatorToCK3/Data_Files/blankMod/output/common/customizable_localization/00_FR_custom_loc.txt
ImperatorToCK3/Data_Files/blankMod/output/common/customizable_localization/00_divinity_custom_loc.txt
ImperatorToCK3/Data_Files/blankMod/output/common/customizable_localization/00_regional_custom_localization.txt
ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_pagan_religion_l_english.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/french/CONVERTER_pagan_religion_l_french.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/german/CONVERTER_pagan_religion_l_german.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/korean/CONVERTER_pagan_religion_l_korean.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/russian/CONVERTER_pagan_religion_l_russian.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/CONVERTER_pagan_religion_l_simp_chinese.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/spanish/CONVERTER_pagan_religion_l_spanish.yml

Customizable_localization

---

ImperatorToCK3/Source/CK3/Titles/Title.cpp
ImperatorToCK3/Source/Imperator/Countries/Countries.cpp

- Added some & to avoid unnecessary copies
- Made the log message about family definitions Debug level

Small tweaks

---

ImperatorToCK3/Source/CK3/CK3World.cpp
ImperatorToCK3/Source/CK3/CK3World.h
ImperatorToCK3/Source/CK3/Titles/LandedTitles.cpp
ImperatorToCK3/Source/CK3/Titles/LandedTitles.h
ImperatorToCK3/Source/CK3/Titles/Title.cpp
ImperatorToCK3/Source/CK3/Titles/Title.h
ImperatorToCK3/Source/CK3Outputter/outTitles.cpp

Fix for vanishing titles

---

ImperatorToCK3/Source/CK3/CK3World.cpp
ImperatorToCK3/Source/CK3/CK3World.h
ImperatorToCK3/Source/CK3/Character/CK3Character.cpp
ImperatorToCK3/Source/CK3/Character/CK3Character.h
ImperatorToCK3/Source/CK3/Province/CK3Province.cpp
ImperatorToCK3/Source/CK3/Province/CK3Province.h
ImperatorToCK3/Source/CK3/Province/CK3ProvinceMappings.cpp
ImperatorToCK3/Source/CK3/Province/CK3ProvinceMappings.h
ImperatorToCK3/Source/CK3/Province/CK3Provinces.cpp
ImperatorToCK3/Source/CK3/Province/CK3Provinces.h
ImperatorToCK3/Source/CK3/Province/ProvinceDetails.cpp
ImperatorToCK3/Source/CK3/Province/ProvinceDetails.h
ImperatorToCK3/Source/CK3/Titles/LandedTitles.cpp
ImperatorToCK3/Source/CK3/Titles/LandedTitles.h
ImperatorToCK3/Source/CK3/Titles/Title.cpp
ImperatorToCK3/Source/CK3/Titles/Title.h
ImperatorToCK3/Source/CK3/Titles/TitlesHistory.cpp
ImperatorToCK3/Source/CK3/Titles/TitlesHistory.h
ImperatorToCK3/Source/CK3Outputter/outTitles.cpp
ImperatorToCK3/Source/Configuration/Configuration.cpp
ImperatorToCK3/Source/Configuration/Configuration.h

Also fixed provinces based on CK3 province mappings having wrong IDs.

Configuration and CK3 namespace refactor

---

ImperatorToCK3/ImperatorToCK3.vcxproj
ImperatorToCK3/ImperatorToCK3.vcxproj.filters
ImperatorToCK3/Source/CK3/CK3World.cpp
ImperatorToCK3/Source/CK3/CK3World.h
ImperatorToCK3/Source/CK3/Province/ProvinceDetails.cpp
ImperatorToCK3/Source/CK3/Province/ProvinceDetails.h
ImperatorToCK3/Source/CK3/Titles/LandedTitles.cpp
ImperatorToCK3/Source/CK3/Titles/Title.cpp
ImperatorToCK3/Source/CK3/Titles/Title.h
ImperatorToCK3/Source/CK3/Titles/TitleHistory.cpp
ImperatorToCK3/Source/CK3/Titles/TitleHistory.h
ImperatorToCK3/Source/CK3/Titles/TitlesHistory.cpp
ImperatorToCK3/Source/CK3/Titles/TitlesHistory.h
ImperatorToCK3/Source/CK3Outputter/outTitles.cpp
ImperatorToCK3/Source/Mappers/RegionMapper/CK3RegionMapper.cpp
ImperatorToCK3Tests/CK3WorldTests/Titles/TitleTests.cpp
ImperatorToCK3Tests/ImperatorToCK3Tests.vcxproj
ImperatorToCK3Tests/ImperatorToCK3Tests.vcxproj.filters
ImperatorToCK3Tests/ImperatorWorldTests/Countries/CountryTests.cpp

Part of #150 
Tests will be added in the second PR for this.

Load vanilla development levels

---

ImperatorToCK3/Source/CK3/CK3World.cpp
ImperatorToCK3/Source/CK3/Titles/TitleHistory.cpp
ImperatorToCK3/Source/CK3/Titles/TitleHistory.h
ImperatorToCK3/Source/CK3/Titles/TitlesHistory.cpp
ImperatorToCK3/Source/CK3/Titles/TitlesHistory.h
ImperatorToCK3Tests/CK3WorldTests/Titles/TitleHistoryTests.cpp
ImperatorToCK3Tests/CK3WorldTests/Titles/TitleTests.cpp
ImperatorToCK3Tests/ImperatorToCK3Tests.vcxproj
ImperatorToCK3Tests/ImperatorToCK3Tests.vcxproj.filters
ImperatorToCK3Tests/TestFiles/TitlesHistory.txt
ImperatorToCK3Tests/TitlesHistory.txt

Added tests for TitleHistory and development level

---

ImperatorToCK3/Data_Files/blankMod/output/common/religion/holy_sites/CONVERTER_holy_sites.txt
ImperatorToCK3/Data_Files/blankMod/output/common/religion/religions/00_kushitism.txt
ImperatorToCK3/Source/CK3/Dynasties/Dynasty.cpp
ImperatorToCK3/Source/CK3/Province/CK3Province.h
ImperatorToCK3/Source/CommonUtilities/History.cpp
ImperatorToCK3/Source/CommonUtilities/HistoryFactory.h
ImperatorToCK3/Source/Imperator/Characters/Characters.cpp
ImperatorToCK3/Source/Imperator/Countries/Countries.cpp
ImperatorToCK3/Source/Imperator/Families/Family.h
ImperatorToCK3/Source/Imperator/Provinces/Provinces.cpp

- ReSharper tweaks
- Fixed encoding of two mod files

Minor tweaks

---

.github/workflows/bump_version_and_create_release.yml
ImperatorToCK3.sln
ImperatorToCK3/Data_Files/blankMod/output/localization/russian/ir_names_l_russian.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/CONVERTER_cultures_l_simp_chinese.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/CONVERTER_pagan_religion_l_simp_chinese.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/ir_deities_l_simp_chinese.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/ir_names_l_simp_chinese.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/spanish/CONVERTER_cultures_l_spanish.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/spanish/CONVERTER_pagan_religion_l_spanish.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/spanish/ir_deities_l_spanish.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/spanish/ir_names_l_spanish.yml

Removed the remaining trailing spaces in loc files

---

ImperatorToCK3/Data_Files/configurables/province_mappings.txt
ImperatorToCK3/Data_Files/configurables/version.txt

- Updated Fronter and googletest
- Updated province mappings for I:R 2.0 and CK3 1.3 (closes #148)

Mappings update

---

ImperatorToCK3/Data_Files/fronter-options.txt
ImperatorToCK3/Data_Files/options_l_english.yml
ImperatorToCK3/Source/CK3Outputter/CK3WorldOutputter.cpp
ImperatorToCK3/Source/CK3Outputter/outLocalization.cpp
ImperatorToCK3/Source/CK3Outputter/outLocalization.h
ImperatorToCK3/Source/CK3Outputter/outTitles.cpp
ImperatorToCK3/Source/CK3Outputter/outTitles.h
ImperatorToCK3/Source/Configuration/Configuration.cpp
ImperatorToCK3/Source/Configuration/Configuration.h

Reenabled ImperatorDeJure option

---

ImperatorToCK3/Source/CK3/CK3World.cpp
ImperatorToCK3/Source/CK3/Titles/Title.cpp
ImperatorToCK3/Source/CK3/Titles/Title.h
ImperatorToCK3/Source/CK3Outputter/outCoas.cpp
ImperatorToCK3/Source/CK3Outputter/outLocalization.cpp
ImperatorToCK3/Source/CK3Outputter/outTitle.cpp
ImperatorToCK3/Source/CK3Outputter/outTitles.cpp
ImperatorToCK3Tests/CK3WorldTests/Titles/LandedTitlesTests.cpp
ImperatorToCK3Tests/CK3WorldTests/Titles/TitleTests.cpp

- Make some fields private
- Merge capital field with capitalCounty field
- Update loc when updating from other title

CK3::Title improvements

---

ImperatorToCK3/Source/CK3/CK3World.cpp
ImperatorToCK3/Source/Imperator/Characters/Characters.cpp
ImperatorToCK3/Source/Imperator/Characters/Characters.h
ImperatorToCK3/Source/Imperator/Provinces/Province.h
ImperatorToCK3/Source/Imperator/Provinces/ProvinceFactory.cpp
ImperatorToCK3/Source/ImperatorToCK3Converter.cpp
ImperatorToCK3/Source/Mappers/LocalizationMapper/LocalizationMapper.cpp
ImperatorToCK3/Source/Mappers/LocalizationMapper/LocalizationMapper.h
ImperatorToCK3/Source/Mappers/ReligionMapper/ReligionMapper.cpp
ImperatorToCK3/Source/Mappers/TagTitleMapper/TagTitleMapper.cpp

Fix float value being read as integer

---

ImperatorToCK3/Source/CK3/CK3World.cpp
ImperatorToCK3/Source/CK3/CK3World.h
ImperatorToCK3/Source/CK3/Character/CK3Character.cpp
ImperatorToCK3/Source/CK3/Character/CK3Character.h
ImperatorToCK3/Source/CK3/Titles/Title.cpp
ImperatorToCK3/Source/CK3/Titles/Title.h
ImperatorToCK3/Source/Imperator/Characters/Character.h
ImperatorToCK3Tests/CK3WorldTests/Titles/TitleTests.cpp

No character is actually purged ATM, because the vanilla characters aren't parsed. Coming in next PR.

Purge landless vanilla characters

---

ImperatorToCK3/Data_Files/blankMod/optionalFiles/ImperatorDeJure/common/landed_titles/zzz_landed_titles.txt
ImperatorToCK3/Data_Files/blankMod/output/history/characters/hellothere.txt
ImperatorToCK3/Data_Files/configurables/version.txt
ImperatorToCK3/Source/CK3/Province/CK3Province.cpp
ImperatorToCK3/Source/CK3/Province/CK3Province.h
ImperatorToCK3/Source/CK3/Titles/Title.cpp
ImperatorToCK3/Source/CK3/Titles/Title.h
ImperatorToCK3/Source/CK3Outputter/CK3WorldOutputter.cpp
ImperatorToCK3/Source/CK3Outputter/outProvince.cpp
ImperatorToCK3/Source/CK3Outputter/outProvinces.cpp
ImperatorToCK3/Source/CK3Outputter/outProvinces.h
ImperatorToCK3/Source/CK3Outputter/outTitles.cpp

- File encoding fixes
- Change outputting of province and title history for CK3 1.4 closes #33
- Change compatible CK3 version

Data files fixes

---

ImperatorToCK3.UnitTests/ImperatorToCK3.UnitTests.csproj
ImperatorToCK3.UnitTests/Mappers/TagTitle/DefiniteFormMapperTests.cs
ImperatorToCK3.UnitTests/TestFiles/configurables/definite_form_names.txt
ImperatorToCK3/CK3/Titles/Title.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Data_Files/configurables/definite_form_names.txt
ImperatorToCK3/Imperator/World.cs
ImperatorToCK3/ImperatorToCK3.csproj
ImperatorToCK3/Mappers/TagTitle/DefiniteFormMapper.cs
ImperatorToCK3/Outputter/TitleOutputter.cs

Configurable set of definite form Imperator names

---

ImperatorToCK3/CK3/Titles/Title.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Data_Files/configurables/governorMappings.txt

Part of #90 
Also cut out some weird region->title mappings.

Skip country adjective when region has 1 governorship

---

ImperatorToCK3/Outputter/TitleOutputter.cs

Output landless=yes

---

ImperatorToCK3.UnitTests/CK3/Dynasties/DynastyTests.cs
ImperatorToCK3.UnitTests/CK3/Titles/TitleTests.cs
ImperatorToCK3.sln.DotSettings
ImperatorToCK3/CK3/Dynasties/Dynasty.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Outputter/DynastiesOutputter.cs

Dynasty serialization

---

ImperatorToCK3/CK3/Characters/Character.cs
ImperatorToCK3/Imperator/Characters/CharacterName.cs

Character name loc key fix

---

ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
ImperatorToCK3.UnitTests/CK3/Dynasties/DynastyTests.cs
ImperatorToCK3/CK3/Characters/Character.cs
ImperatorToCK3/CK3/Characters/Characters.cs
ImperatorToCK3/CK3/Titles/Title.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Converter.cs
ImperatorToCK3/Imperator/Characters/Character.cs
ImperatorToCK3/Imperator/Characters/Characters.cs
ImperatorToCK3/Outputter/CharacterOutputter.cs
ImperatorToCK3/Outputter/CharactersOutputter.cs
ImperatorToCK3/Outputter/TitlesOutputter.cs
ImperatorToCK3/Outputter/WorldOutputter.cs

Imprisonment conversion

---

ImperatorToCK3.UnitTests/Imperator/Characters/CharacterTests.cs
ImperatorToCK3/CK3/Characters/Character.cs
ImperatorToCK3/CK3/Characters/Characters.cs
ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Imperator/Characters/Character.cs
ImperatorToCK3/Imperator/Characters/Characters.cs
ImperatorToCK3/Outputter/CharacterOutputter.cs

Set employer for every unlanded character from Imperator

---

ImperatorToCK3.UnitTests/CommonUtils/HistoryTests.cs
ImperatorToCK3/CK3/Provinces/ProvinceDetails.cs
ImperatorToCK3/CK3/Titles/TitlesHistory.cs
ImperatorToCK3/CommonUtils/DatedHistoryBlock.cs
ImperatorToCK3/CommonUtils/HistoryFactory.cs

Builder pattern for HistoryFactory initialization

---

ImperatorToCK3.UnitTests/CK3/Titles/TitleTests.cs
ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/Titles/Title.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Outputter/CoatOfArmsOutputter.cs
ImperatorToCK3/Outputter/ProvincesOutputter.cs
ImperatorToCK3/Outputter/TitlesOutputter.cs

I know, another refactor... But this combines the simple interface of the solution from #405 with good encapsulation. This is the way.

Better encapsulation for LandedTitles

---

ImperatorToCK3/CK3/Provinces/Province.cs
ImperatorToCK3/Data_Files/configurables/succession_law_map.txt
ImperatorToCK3/Outputter/SuccessionTriggersOutputter.cs
ImperatorToCK3/Outputter/WorldOutputter.cs

Add Succession Law Title Exception for Primogeniture/Seniority

Add Succession Law Title Exception for Primogeniture/Seniority

---

ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/01_aboriginal.txt

Make Nuragic culture's gfx same as Basque's

---

ImperatorToCK3/CK3/Provinces/Province.cs

 Use country's religion and primary culture as a fallback for provinces

---

ImperatorToCK3/CK3/Characters/Character.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Converter.cs
ImperatorToCK3/Imperator/Countries/CountryName.cs
ImperatorToCK3/Imperator/World.cs
ImperatorToCK3/Outputter/WorldOutputter.cs

Fix broken history output on BC conversion date

---

ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
ImperatorToCK3.UnitTests/CK3/Provinces/ProvinceTests.cs
ImperatorToCK3.UnitTests/CK3/Titles/LandedTitlesTests.cs
ImperatorToCK3.UnitTests/CK3/Titles/TitleTests.cs
ImperatorToCK3.UnitTests/Mappers/Culture/CultureMappingTests.cs
ImperatorToCK3.UnitTests/Mappers/Region/CK3RegionMapperTests.cs
ImperatorToCK3.UnitTests/Mappers/Region/CK3RegionTests.cs
ImperatorToCK3.UnitTests/Mappers/Religion/ReligionMappingTests.cs
ImperatorToCK3.sln.DotSettings
ImperatorToCK3/CK3/Characters/CharacterCollection.cs
ImperatorToCK3/CK3/Provinces/Province.cs
ImperatorToCK3/CK3/Provinces/ProvinceCollection.cs
ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/Titles/RulerTerm.cs
ImperatorToCK3/CK3/Titles/Title.cs
ImperatorToCK3/CK3/Titles/TitleCollection.cs
ImperatorToCK3/CK3/Titles/TitleHistory.cs
ImperatorToCK3/CK3/Titles/TitlesHistory.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Mappers/Region/CK3Region.cs
ImperatorToCK3/Mappers/Region/CK3RegionMapper.cs
ImperatorToCK3/Outputter/BookmarkOutputter.cs
ImperatorToCK3/Outputter/CoatOfArmsOutputter.cs
ImperatorToCK3/Outputter/ProvincesOutputter.cs
ImperatorToCK3/Outputter/SuccessionTriggersOutputter.cs
ImperatorToCK3/Outputter/TitlesOutputter.cs

Achieved this by making Title constructors private and making LandedTitles a nested class of Title.

Make Title only constructible through LandedTitles

---

ImperatorToCK3/CK3/Titles/Title.cs

Fix government change by country's current ruler being ignored

---

ImperatorToCK3.UnitTests/Imperator/Countries/CountryTests.cs
ImperatorToCK3.UnitTests/TestFiles/CK3/game/common/governments/governments.txt
ImperatorToCK3.UnitTests/TestFiles/documents/CK3/mod/cool_mod/common/governments/governments.txt
ImperatorToCK3/Configuration.cs
ImperatorToCK3/Imperator/Countries/Country.cs
ImperatorToCK3/Imperator/Countries/CountryFactory.cs
ImperatorToCK3/Imperator/World.cs
ImperatorToCK3/Mappers/Localization/LocalizationMapper.cs

Dehardcoded determining of government type with support for mod governments

---

ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Mappers/CoA/CoaMapper.cs

Support mod CoAs

---

ImperatorToCK3/Converter.cs
ImperatorToCK3/Outputter/ColoredEmblemsOutputter.cs
ImperatorToCK3/Outputter/WorldOutputter.cs

Copy mods' colored emblems to generated CK3 mod

---

ImperatorToCK3/Data_Files/configurables/province_mappings.txt

Added Southern Iberian Peninsula mappings

Added Southern Iberian Peninsula mappings

---

ImperatorToCK3.UnitTests/Mappers/Region/ImperatorRegionMapperTests.cs
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test1/game/map_data/regions.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test2/game/map_data/areas.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test2/game/map_data/regions.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test3/game/map_data/areas.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test3/game/map_data/regions.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test4/game/map_data/areas.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test4/game/map_data/regions.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test5/game/map_data/areas.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test5/game/map_data/regions.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test6/game/map_data/areas.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test6/game/map_data/regions.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test7/game/map_data/areas.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test7/game/map_data/regions.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test8/CK3/game/map_data/areas.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test8/CK3/game/map_data/regions.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test8/mod1/map_data/areas.txt
ImperatorToCK3.UnitTests/TestFiles/ImperatorRegionMapper/test8/mod1/map_data/regions.txt
ImperatorToCK3.sln.DotSettings
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Mappers/Region/ImperatorRegionMapper.cs

Read mods' areas and regions

---

ImperatorToCK3.UnitTests/Outputter/SuccessionTriggersOutputterTests.cs
ImperatorToCK3/CK3/Titles/Title.cs
ImperatorToCK3/Outputter/SuccessionTriggersOutputter.cs

Fix succession laws not being converted

---

ImperatorToCK3/Outputter/BookmarkOutputter.cs

Part of Magick.NET replacement #378.

Use ImageSharp to resize provinces.png

---

ImperatorToCK3/Data_Files/configurables/province_mappings.txt

Update province mappings for CK3 1.5

---

ImperatorToCK3.sln.DotSettings
ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_berber_new.txt
ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_brythonic_new.txt
ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_iranian_new.txt
ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_israelite_new.txt
ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_latin_override.txt
ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_mongolic_new.txt
ImperatorToCK3/Data_Files/blankMod/output/common/culture/name_lists/IRToCK3_latin_override.txt
ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_cultures_l_english.yml
ImperatorToCK3/ImperatorToCK3.csproj

Update gfx for some of our cultures

---

ImperatorToCK3/Data_Files/configurables/culture_map.txt

part of #252 
Suggested by @Arcvalons:
https://forum.paradoxplaza.com/forum/threads/imperator-to-ck3-release-thread.1415172/post-27763343

Map Magadhi culture to Bengali

---

ImperatorToCK3/Data_Files/configurables/title_map.txt

Remove duchies from mappings in `configurables/title_map.txt`

---

ImperatorToCK3/Data_Files/blankMod/output/common/religion/religions/00_germanic.txt
ImperatorToCK3/Data_Files/blankMod/output/common/religion/religions/00_hellenism.txt

Update modified vanilla files to CK3 1.5.1.1

---

ImperatorToCK3.UnitTests/CK3/Titles/LandedTitlesTests.cs
ImperatorToCK3.UnitTests/Imperator/Countries/CountryTests.cs
ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/Titles/Title.cs
ImperatorToCK3/Outputter/BookmarkOutputter.cs

Make governoship colors different from liege one

---

ImperatorToCK3/Data_Files/configurables/province_mappings.txt

… in Northern Italy (old mapping)

Some new province mappings for Denmark, one small adjustment in Northern Italy

---

ImperatorToCK3/CK3/Provinces/Province.cs

Make unmapped culture and religion logging Error level

---

ImperatorToCK3/Data_Files/configurables/province_mappings.txt

Benelux + Mapping Holes Cover Up

Benelux + Mapping Holes Cover Up

---

ImperatorToCK3/Data_Files/configurables/province_mappings.txt

Wallachia mappings

---

ImperatorToCK3.UnitTests/Mappers/HolySiteEffect/HolySiteEffectMapperTests.cs
ImperatorToCK3.UnitTests/TestFiles/HolySiteEffectMapperTests/mappings.txt
ImperatorToCK3/Mappers/HolySiteEffect/HolySiteEffectMapper.cs

HolySiteEffectMapper

---

ImperatorToCK3/Data_Files/configurables/province_mappings.txt

New North Serbia Mappings + small correction in Wallachia

New North Serbia Mappings + small correction in Wallachia

---

ImperatorToCK3/Data_Files/configurables/province_mappings.txt

New Carpathia mappings

---

ImperatorToCK3/Data_Files/configurables/governorMappings.txt
ImperatorToCK3/Data_Files/configurables/title_map.txt

based on https://forum.paradoxplaza.com/forum/threads/imperator-to-ck3-release-thread.1415172/post-28312826

Title mapping and governorship mapping tweaks

---

ImperatorToCK3/Data_Files/configurables/culture_map.txt
ImperatorToCK3/Data_Files/configurables/governorMappings.txt
ImperatorToCK3/Data_Files/configurables/title_map.txt

https://forum.paradoxplaza.com/forum/threads/imperator-to-ck3-release-thread.1415172/post-28368710

Mapping tweaks by Vielus

---

ImperatorToCK3.UnitTests/Imperator/Provinces/ProvinceTests.cs
ImperatorToCK3/CK3/Provinces/Province.cs
ImperatorToCK3/Imperator/Provinces/Province.cs
ImperatorToCK3/Imperator/Provinces/ProvinceFactory.cs

Rename Imperator Province's Religion property to ReligionId

---

ImperatorToCK3/Data_Files/configurables/holy_site_effect_mappings.txt

Revised holy effects

---

ImperatorToCK3/Data_Files/configurables/holy_site_effect_mappings.txt

reinstated prestige holy site effect

Holy site effect review

---

ImperatorToCK3/CK3/Dynasties/DynastyCollection.cs
ImperatorToCK3/CK3/Map/MapData.cs
ImperatorToCK3/CK3/Provinces/ProvinceCollection.cs
ImperatorToCK3/CK3/Religions/ReligionCollection.cs
ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/Imperator/Provinces/ProvinceCollection.cs
ImperatorToCK3/Imperator/Religions/ReligionCollection.cs
ImperatorToCK3/Mappers/CoA/CoaMapper.cs
ImperatorToCK3/Mappers/Culture/CultureMapper.cs
ImperatorToCK3/Mappers/DeathReason/DeathReasonMapper.cs
ImperatorToCK3/Mappers/Government/GovernmentMapper.cs
ImperatorToCK3/Mappers/Nickname/NicknameMapper.cs
ImperatorToCK3/Mappers/Province/ProvinceMapper.cs
ImperatorToCK3/Mappers/Region/CK3RegionMapper.cs
ImperatorToCK3/Mappers/Region/ImperatorRegionMapper.cs
ImperatorToCK3/Mappers/Religion/ReligionMapper.cs
ImperatorToCK3/Mappers/SuccessionLaw/SuccessionLawMapper.cs
ImperatorToCK3/Mappers/TagTitle/TagTitleMapper.cs
ImperatorToCK3/Mappers/Trait/TraitMapper.cs
ImperatorToCK3/Outputter/WorldOutputter.cs

Progress logging

---

ImperatorToCK3/Data_Files/configurables/holy_site_effect_mappings.txt

Update of factors for holy site effect

Update of factors for holy site effect

---

ImperatorToCK3.UnitTests/CK3/Characters/CharacterCollectionTests.cs
ImperatorToCK3.UnitTests/CK3/Titles/LandedTitlesTests.cs
ImperatorToCK3.UnitTests/Mappers/TagTitle/TagTitleMapperTests.cs
ImperatorToCK3.UnitTests/Outputter/CoatOfArmsOutputterTests.cs
ImperatorToCK3/CK3/Dynasties/Dynasty.cs
ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Outputter/CoatOfArmsOutputter.cs
ImperatorToCK3/Outputter/ColoredEmblemsOutputter.cs
ImperatorToCK3/Outputter/NamedColorsOutputter.cs
ImperatorToCK3/Outputter/WorldOutputter.cs

Output ruling dynasty CoAs

---

ImperatorToCK3/Data_Files/configurables/culture_map.txt

Add missing culture mappings for Invictus

---

ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
ImperatorToCK3.UnitTests/CK3/Dynasties/DynastyTests.cs
ImperatorToCK3.UnitTests/Imperator/Families/FamilyTests.cs
ImperatorToCK3.UnitTests/Outputter/DynastiesOutputterTests.cs
ImperatorToCK3/CK3/Dynasties/Dynasty.cs
ImperatorToCK3/CK3/Dynasties/DynastyCollection.cs
ImperatorToCK3/Imperator/Characters/Character.cs
ImperatorToCK3/Imperator/Families/Family.cs
ImperatorToCK3/Imperator/Families/FamilyCollection.cs
ImperatorToCK3/Imperator/World.cs

Try to merge divided Imperator families

---

ImperatorToCK3.sln.DotSettings
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Data_Files/blankMod/output/common/flavorization/CONVERTER_title_holders.txt
ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_title_names_l_english.yml

Expand Eremitic ruler generation to Faroe Islands

---

ImperatorToCK3.UnitTests/CK3/Titles/LandedTitlesTests.cs
ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Configuration.cs
ImperatorToCK3/Data_Files/fronter_configuration/fronter-options.txt
ImperatorToCK3/Data_Files/fronter_configuration/options_l_english.yml

Make I:R civilization level to CK3 development ratio configurable

---

ImperatorToCK3/Imperator/World.cs
ImperatorToCK3/Outputter/CoatOfArmsOutputter.cs
ImperatorToCK3/Outputter/LocalizationOutputter.cs
ImperatorToCK3/Outputter/WorldOutputter.cs

Improve I:R mods support

---

ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
ImperatorToCK3.UnitTests/CK3/Dynasties/DynastyTests.cs
ImperatorToCK3.UnitTests/Outputter/DynastiesOutputterTests.cs
ImperatorToCK3/CK3/Dynasties/Dynasty.cs
ImperatorToCK3/CK3/Dynasties/DynastyCollection.cs
ImperatorToCK3/Data_Files/blankMod/output/common/culture/name_lists/IRToCK3_zz_whatif.txt
ImperatorToCK3/Imperator/Cultures/Culture.cs
ImperatorToCK3/Imperator/Cultures/CultureGroup.cs
ImperatorToCK3/Imperator/Cultures/CulturesDB.cs
ImperatorToCK3/Imperator/Families/Family.cs
ImperatorToCK3/Imperator/World.cs

Use male family form (e.g. Julius) instead of plural (e.g. Julii) for dynasty name if possible

---

ImperatorToCK3.sln.DotSettings
ImperatorToCK3/CK3/Titles/Title.cs

Improve loc generation from PRY, SEL and MRY tags

---

ImperatorToCK3/Data_Files/configurables/province_mappings.txt

Invictus Morocco mappings

---

ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
ImperatorToCK3/CK3/Characters/Character.cs
ImperatorToCK3/Imperator/Characters/CharacterAttributes.cs

Convert character attributes

---

ImperatorToCK3/Data_Files/blankMod/output/common/customizable_localization/99_fr_custom_loc.txt
ImperatorToCK3/Data_Files/blankMod/output/common/on_action/game_start.txt

Blank mod compatch for CK3 1.7

---

ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Data_Files/configurables/province_mappings.txt

Eastern Europe province mappings improvements for Invictus

---

ImperatorToCK3/Data_Files/configurables/province_mappings.txt

Redone Poland province mappings

---

ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_iranian_new.txt
ImperatorToCK3/Data_Files/converter_globals/ReadMe.txt

Add more traditions to Scythian and Sarmatian cultures

---

ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_chaldean.txt

Change Aramaic cultural traditions

---

ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_iranian_new.txt

Co-Authored-By: nah34 <101521284+nah34@users.noreply.github.com>
#988

Add more traditions to Bactrian culture

---

ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/Titles/Title.cs

Also comes with improved comments.

Replace IsImportedOrUpdatedFromImperator with IsCreatedFromImperator

---

ImperatorToCK3/ImperatorToCK3.csproj

This reverts commit 4fb414e994ee1d8ce7e0a0f8609d393b0ba0b943.

Revert "Build frontend when building the converter (#1063) #patch"

---

ImperatorToCK3.UnitTests/CK3/Dynasties/DynastyTests.cs
ImperatorToCK3.UnitTests/Outputter/DynastiesOutputterTests.cs
ImperatorToCK3/CK3/Dynasties/Dynasty.cs
ImperatorToCK3/Imperator/Families/Family.cs
ImperatorToCK3/ImperatorToCK3.csproj
ImperatorToCK3/Outputter/LocalizationOutputter.cs

Fix some dynasties having no names

---

ImperatorToCK3.UnitTests/Imperator/Countries/CountryTests.cs
ImperatorToCK3/CK3/Characters/Character.cs
ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/Titles/Title.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Imperator/Countries/Country.cs
ImperatorToCK3/Imperator/Countries/CountryFactory.cs
ImperatorToCK3/Imperator/Provinces/Province.cs
ImperatorToCK3/Imperator/Provinces/ProvinceFactory.cs

Convert holding owners to barony holders

---

ImperatorToCK3.sln.DotSettings
ImperatorToCK3/Configuration.cs

Raise exception if configuration.txt is not found

---

ImperatorToCK3/Outputter/CharacterOutputter.cs

Don't output traits and attributes of dead characters to speed up game loading

---

ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
ImperatorToCK3.UnitTests/CK3/Religions/FaithTests.cs
ImperatorToCK3.UnitTests/CK3/Religions/HolySiteTests.cs
ImperatorToCK3.UnitTests/CK3/Religions/ReligionCollectionTests.cs
ImperatorToCK3.UnitTests/CK3/Religions/ReligionTests.cs
ImperatorToCK3.UnitTests/CK3/Titles/RulerTermTests.cs
ImperatorToCK3.UnitTests/Mappers/Religion/ReligionMapperTests.cs
ImperatorToCK3/CK3/Characters/Character.cs
ImperatorToCK3/CK3/Cultures/Culture.cs
ImperatorToCK3/CK3/Cultures/CultureCollection.cs
ImperatorToCK3/CK3/Cultures/Pillar.cs
ImperatorToCK3/CK3/Cultures/PillarCollection.cs
ImperatorToCK3/CK3/Dynasties/Dynasty.cs
ImperatorToCK3/CK3/Religions/Faith.cs
ImperatorToCK3/CK3/Religions/Religion.cs
ImperatorToCK3/CK3/Religions/ReligionCollection.cs
ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/Titles/Title.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Outputter/BookmarkOutputter.cs

Fill gaps in de jure empire setup with empires generated from cultural heritages

---

ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/Titles/Title.cs
ImperatorToCK3/Configuration.cs
ImperatorToCK3/Data_Files/fronter_configuration/fronter-options.txt
ImperatorToCK3/Data_Files/fronter_configuration/options_l_english.yml

Add an option to decide whether I:R or CK3 flag should be preferred

---

ImperatorToCK3.UnitTests/CK3/Religions/FaithTests.cs
ImperatorToCK3.UnitTests/CK3/Religions/HolySiteTests.cs
ImperatorToCK3/CK3/Characters/Character.cs
ImperatorToCK3/CK3/Cultures/Culture.cs
ImperatorToCK3/CK3/Cultures/CultureCollection.cs
ImperatorToCK3/CK3/Cultures/NameList.cs
ImperatorToCK3/CK3/Religions/DoctrineCategory.cs
ImperatorToCK3/CK3/Religions/Faith.cs
ImperatorToCK3/CK3/Religions/Religion.cs
ImperatorToCK3/CK3/Religions/ReligionCollection.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/ImperatorToCK3.csproj

Generate religious heads for faiths with Spiritual Head of Faith doctrine

---

ImperatorToCK3/CK3/Characters/CharacterCollection.cs
ImperatorToCK3/CommonUtils/LiteralHistoryField.cs
ImperatorToCK3/Imperator/Characters/Character.cs

Convert friendships and rivalries from Imperator

---

ImperatorToCK3/CK3/Characters/Character.cs
ImperatorToCK3/Imperator/Characters/Character.cs

Convert character health from Imperator

---

ImperatorToCK3.sln.DotSettings
ImperatorToCK3/CK3/Characters/Character.cs
ImperatorToCK3/CK3/Cultures/NameList.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Configuration.cs
ImperatorToCK3/Data_Files/fronter_configuration/fronter-options.txt
ImperatorToCK3/Data_Files/fronter_configuration/options_l_english.yml
global.json

Add an option to generate dukes instead of counts for unowned areas

---

ImperatorToCK3.UnitTests/CK3/Characters/ColorDNAGeneValueTests.cs
ImperatorToCK3.UnitTests/CK3/Characters/DNAGeneValueTests.cs
ImperatorToCK3/CK3/Characters/DNA.cs
ImperatorToCK3/CK3/Characters/DNAColorGeneValue.cs
ImperatorToCK3/CK3/Characters/DNAFactory.cs
ImperatorToCK3/CK3/Characters/DNAGeneValue.cs
ImperatorToCK3/Data_Files/configurables/accessory_genes_map.txt

For example [Antigonus I Monophthalmus](https://en.wikipedia.org/wiki/Antigonus_I_Monophthalmus) will now be one-eyed on bookmark screen.

Convert portrait eyepatches, blindfolds, blind eyes and red eyes

---

ImperatorToCK3/Converter.cs
ImperatorToCK3/Helpers/MusicPlayer.cs
ImperatorToCK3/ImperatorToCK3.csproj

Play initially I:R and later CK3 music during the conversion

---

ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
ImperatorToCK3.UnitTests/CK3/Dynasties/DynastyTests.cs
ImperatorToCK3.UnitTests/CK3/Titles/RulerTermTests.cs
ImperatorToCK3.UnitTests/Mappers/Culture/CultureMapperTests.cs
ImperatorToCK3.UnitTests/Mappers/Culture/CultureMappingTests.cs
ImperatorToCK3.UnitTests/Mappers/Province/ProvinceMappingTests.cs
ImperatorToCK3.UnitTests/Mappers/Religion/ReligionMapperTests.cs
ImperatorToCK3.UnitTests/Mappers/Religion/ReligionMappingTests.cs
ImperatorToCK3/CK3/Characters/Character.cs
ImperatorToCK3/CK3/Dynasties/Dynasty.cs
ImperatorToCK3/CK3/Provinces/Province.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Data_Files/configurables/culture_map.txt
ImperatorToCK3/Data_Files/configurables/religion_map.txt
ImperatorToCK3/Mappers/Culture/CultureMapper.cs
ImperatorToCK3/Mappers/Culture/CultureMappingRule.cs
ImperatorToCK3/Mappers/Religion/ReligionMapper.cs
ImperatorToCK3/Mappers/Religion/ReligionMapping.cs

Add `ck3Culture` as optional parameter in religion mappings

---

ImperatorToCK3/Data_Files/blankMod/output/common/culture/creation_names/IRToCK3_names.txt

Fix script errors in converter's culture creation names

---

ImperatorToCK3/Mappers/Region/CK3Region.cs
ImperatorToCK3/Mappers/Region/CK3RegionMapper.cs
ImperatorToCK3/Mappers/Region/ImperatorRegion.cs
ImperatorToCK3/Mappers/Region/ImperatorRegionMapper.cs

This prevents exception caused by error in latest TFE mod version.

Don't throw exceptions on CK3 regions referencing missing duchies

---

ImperatorToCK3/Data_Files/configurables/converter_cultures.txt

Prevent duplicate Carthaginian, Hun and Kemetic cultures with TFE

---

ImperatorToCK3.UnitTests/CK3/Titles/TitleTests.cs
ImperatorToCK3/CK3/Provinces/Province.cs
ImperatorToCK3/CK3/Religions/ReligionCollection.cs
ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/Titles/Title.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Mappers/Region/CK3Region.cs
ImperatorToCK3/Mappers/Region/CK3RegionMapper.cs
ImperatorToCK3/Mappers/TagTitle/Mapping.cs
ImperatorToCK3/Mappers/TagTitle/TagTitleMapper.cs

Sentry event ID: 6a21957012454c3f9a7267777859cfd3

Fix exception when using unsupported CK3 map mod combinations

---

ImperatorToCK3/ImperatorToCK3.csproj
ImperatorToCK3/app.manifest

Sentry event ID: 4381941269344bf7ab04d24d90bcbff4

Require administrator permissions for converter backend

---

ImperatorToCK3/Outputter/WorldOutputter.cs

Sentry event ID: 9c2136c419ef43d4975b461a7c915338

Handle IOException when clearing the mod output folder

---

ImperatorToCK3/CommonUtils/FileOpeningHelper.cs
ImperatorToCK3/ImperatorToCK3.csproj
ImperatorToCK3/Outputter/BookmarkOutputter.cs
ImperatorToCK3/Outputter/CharactersOutputter.cs
ImperatorToCK3/Outputter/CulturesOutputter.cs
ImperatorToCK3/Outputter/DynastiesOutputter.cs
ImperatorToCK3/Outputter/LocalizationOutputter.cs
ImperatorToCK3/Outputter/MenAtArmsOutputter.cs
ImperatorToCK3/Outputter/NamedColorsOutputter.cs
ImperatorToCK3/Outputter/PillarOutputter.cs
ImperatorToCK3/Outputter/ProvincesOutputter.cs
ImperatorToCK3/Outputter/ReligionsOutputter.cs
ImperatorToCK3/Outputter/SuccessionTriggersOutputter.cs
ImperatorToCK3/Outputter/TitlesOutputter.cs
ImperatorToCK3/Outputter/WarsOutputter.cs
ImperatorToCK3/Outputter/WorldOutputter.cs

Related Sentry event ID: 3b8b48f6402d488484a0b3b86a6056bf

Handle file sharing violation when trying to write a file

---

ImperatorToCK3.UnitTests/CK3/Titles/LandedTitlesTests.cs
ImperatorToCK3.UnitTests/CK3/Titles/TitleTests.cs
ImperatorToCK3/CK3/Religions/HolySite.cs
ImperatorToCK3/CK3/Religions/ReligionCollection.cs
ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/Titles/Title.cs

Sentry event ID: 6eb5901b16094e61aa83d18b9d01d54a

Fix InvalidOperationException when importing characters

---

ImperatorToCK3/CK3/World.cs

Sentry event ID: 5bebcee7367f4b65ad6deee6a7deec67

Prevent KeyNotFoundException when generating a hermit for Iceland

---

ImperatorToCK3/CK3/Cultures/CultureCollection.cs
ImperatorToCK3/CK3/Cultures/PillarCollection.cs
ImperatorToCK3/CK3/Religions/Religion.cs

Fix Fyrnsidu faith having 6 tenets and 10 holy sites in generated mods

---

ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Data_Files/configurables/province_mappings.txt

Fix CK3 province 1727 being unmapped

---

ImperatorToCK3.UnitTests/CK3/Characters/CharacterCollectionTests.cs
ImperatorToCK3.UnitTests/CK3/Titles/LandedTitlesTests.cs
ImperatorToCK3.UnitTests/CK3/Titles/TitleTests.cs
ImperatorToCK3.UnitTests/Mappers/TagTitle/MappingTests.cs
ImperatorToCK3.UnitTests/Mappers/TagTitle/TagTitleMapperTests.cs
ImperatorToCK3.UnitTests/Outputter/CoatOfArmsOutputterTests.cs
ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/Titles/Title.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Helpers/EnumHelper.cs
ImperatorToCK3/Imperator/Diplomacy/Dependency.cs
ImperatorToCK3/Imperator/Diplomacy/DiplomacyDB.cs
ImperatorToCK3/Imperator/World.cs
ImperatorToCK3/Mappers/TagTitle/Mapping.cs
ImperatorToCK3/Mappers/TagTitle/TagTitleMapper.cs

Part of #923, can be improved a lot.

Very basic subject-to-vassal conversion

---

ImperatorToCK3/Outputter/CoatOfArmsEmblemsOutputter.cs

closes #1793 
In my last test run it took 7 seconds.

Parallelize the conversion of colored emblems

---

ImperatorToCK3/Data_Files/blankMod/output/common/culture/name_lists/IRToCK3_berber.txt
ImperatorToCK3/Data_Files/blankMod/output/common/flavorization/CONVERTER_title_holders.txt
ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_culture_name_lists_l_english.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_cultures_l_english.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_title_names_l_english.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/french/01_culture_name_lists_l_french.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/french/CONVERTER_cultures_l_french.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/french/CONVERTER_title_names_l_french.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/german/01_culture_name_lists_l_german.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/german/CONVERTER_cultures_l_german.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/german/CONVERTER_title_names_l_german.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/korean/01_culture_name_lists_l_korean.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/korean/CONVERTER_cultures_l_korean.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/korean/CONVERTER_title_names_l_korean.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/russian/01_culture_name_lists_l_russian.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/russian/CONVERTER_cultures_l_russian.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/russian/CONVERTER_title_names_l_russian.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/01_culture_name_lists_l_simp_chinese.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/CONVERTER_cultures_l_simp_chinese.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/CONVERTER_title_names_l_simp_chinese.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/spanish/01_culture_name_lists_l_spanish.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/spanish/CONVERTER_cultures_l_spanish.yml
ImperatorToCK3/Data_Files/blankMod/output/localization/spanish/CONVERTER_title_names_l_spanish.yml
ImperatorToCK3/Data_Files/configurables/converter_cultures.txt
ImperatorToCK3/Data_Files/configurables/converter_faiths.txt
ImperatorToCK3/Data_Files/configurables/culture_map.txt

Prefer vanilla CK3 Ancient Egyptian culture over converter's one

---

ImperatorToCK3.UnitTests/CK3/Cultures/CultureCollectionTests.cs
ImperatorToCK3.UnitTests/TestFiles/CK3/game/common/culture/cultures/test_cultures.txt
ImperatorToCK3/CK3/Cultures/CultureCollection.cs

Sentry event ID: 6a18841dcfef4bedb55ac534d6c96b65

Don't load cultures without a valid language

---

ImperatorToCK3/Data_Files/configurables/wargoal_mappings.txt

Add mappings for Invictus war goals

---

ImperatorToCK3/CK3/Characters/Character.cs
ImperatorToCK3/Imperator/Characters/Character.cs

Convert character fertility

---

ImperatorToCK3/CK3/Legends/LegendSeed.cs
ImperatorToCK3/CK3/Legends/LegendSeedCollection.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Data_Files/configurables/legend_seeds_to_remove.txt
ImperatorToCK3/Outputter/WorldOutputter.cs

Remove anachronistic legend seeds

---

ImperatorToCK3/CK3/Characters/DNAFactory.cs
ImperatorToCK3/CommonUtils/Genes/AccessoryGeneTemplate.cs
ImperatorToCK3/Data_Files/configurables/religion_map.txt

Sentry event ID: 1f6dd3eccb5f43b09d9feb735a716daf

Make DNA conversion less likely to throw an exception when a gene template has no weight block for given age and sex

---

ImperatorToCK3/Mappers/TagTitle/TagTitleMapper.cs

Sentry event ID: 37a9fed8f2c64cf8a66e2e52f380f546

Fix InvalidOperationException while converting governorships

---

ImperatorToCK3/CommonUtils/Map/MapData.cs

Sentry event ID: 08db0b07237b4437a57493f62363e30e

Fix exception when loading adjacency with empty source or target

---

ImperatorToCK3/CK3/Religions/ReligionCollection.cs

Sentry event ID: ee005e56b7434ce4925e015ef458982c

Prevent missing religious head character from causing an exception

---

ImperatorToCK3/CK3/Titles/Title.cs

Sentry event ID: bb8e3c8d234d4baf81567486b485ad3c

Fix ArgumentOutOfRangeException while generating title adjective

---

ImperatorToCK3/Imperator/Inventions/InventionsDB.cs

Sentry event ID: d7bdc511483a459c83214012a1fb3f9b

Prevent exception when checking active inventions for country

---

ImperatorToCK3/Outputter/BookmarkOutputter.cs

This makes the OutputBookmark method less complex.

Extract AddTitleToBookmarkScreen

---

ImperatorToCK3/CK3/Cultures/CultureCollection.cs
ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Mappers/Technology/InnovationBonus.cs
ImperatorToCK3/Mappers/Technology/InnovationLink.cs
ImperatorToCK3/Mappers/Technology/InnovationMapper.cs

Fix for TFE compatibility: load innovations from CK3 and remove invalid technology mappings

---

ImperatorToCK3.UnitTests/Mappers/Technology/InnovationBonusTests.cs
ImperatorToCK3.UnitTests/Mappers/Technology/InnovationLinkTests.cs
ImperatorToCK3/Mappers/Technology/InnovationBonus.cs
ImperatorToCK3/Mappers/Technology/InnovationLink.cs

+ unit tests for InnovationLink and InnovationBonus

Log a warning when an innovation bonus mapping has no I:R entries

---

ImperatorToCK3/Helpers/RakalyCaller.cs

Sentry event ID: d87276c4e79a4093b7312b3397d543b3

Log a user-friendly message when Rakaly executable is not found

---

ImperatorToCK3/CK3/Characters/CharactersLoader.cs

This will reduce the size of the outputted mod.

Simplify outputted birth entries of loaded CK3 characters

---

ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/World.cs

Sentry event ID: bde0ac9fc3ba47c2a076065a283f5012

Fix exception while carving titles

---

ImperatorToCK3/Helpers/RakalyCaller.cs

Sentry event ID: 8c7ab9ed5e204ef0a90421c059fc05c9

Better handle "Failed to create melted file" Rakaly error

---

ImperatorToCK3/CommonUtils/ConcurrentIgnoredKeywordsSet.cs
ImperatorToCK3/CommonUtils/IgnoredKeywordsSet.cs
ImperatorToCK3/Imperator/Characters/Character.cs
ImperatorToCK3/Imperator/Characters/CharacterCollection.cs
ImperatorToCK3/ImperatorToCK3.csproj

The loading is now implented using the producer-consumer pattern, with multiple consumers.

Speed up the loading of Imperator characters

---

ImperatorToCK3/Data_Files/configurables/culture_map.txt
ImperatorToCK3/Data_Files/configurables/religion_map.txt

Religion mappings for Invictus 1.8

---

ImperatorToCK3/CommonUtils/FileHelper.cs
ImperatorToCK3/Helpers/RakalyCaller.cs

Sentry event ID: c6906d772f8c4d08b54ac0cdf46c9d8f

Make multiple attempts to move the melted save file if it's used by another process

---

ImperatorToCK3/Outputter/LocalizationOutputter.cs

Sentry event ID: 882a6a36d890403fbc6cf921de9295ef

Fix AggregateException when outputting localization

---

ImperatorToCK3/Configuration.cs

Sentry event ID: 586e6a384e1446f2b8a6036429aec830

Verify the entered Imperator documents path after reading the configuration

---

ImperatorToCK3/Data_Files/configurables/removable_file_blocks.txt

Thanks to @tanner918 for noticing that it was being applied.

Prevent "Backwater" county modifier being applied to Greece

---

.github/workflows/build.yml
.github/workflows/build_dev_version.yml
.github/workflows/create_release.yml
.github/workflows/test.yml
ImperatorToCK3/Data_Files/configurables/title_map.txt
global.json

Remove mapping from BYZ to e_byzantium

---

ImperatorToCK3/Data_Files/configurables/converter_cultures.txt

Specifically, Culture Blending and Warrior Culture.

Add two traditions to Hellenistic culture

---

ImperatorToCK3/CK3/Characters/DNAFactory.cs

Sentry event ID: 2454b92b077e42088ba9b3e3e777f5b3
Issue seems to occur when EPE is included in the CK3 mods.

Fix exception if the `special_headgear_blindfold` gene is not found

---

ImperatorToCK3/Data_Files/blankMod/output/localization/replace/english/zzz_IRToCK3_vanilla_override_l_english.yml

Rename Ancient Egyptian to Kemetic and Egyptian to Misri

---

ImperatorToCK3/Data_Files/configurables/removable_file_blocks_aep.txt
ImperatorToCK3/Data_Files/configurables/replaceable_file_blocks_aep.txt
ImperatorToCK3/Outputter/FileTweaker.cs

"Partially" because it seems the equivalent vanilla file is actually used in AEP.

Partially fix random Muslim and Christian characters being spawned in AEP

---

ImperatorToCK3/CK3/Religions/Faith.cs
ImperatorToCK3/CK3/Religions/ReligionCollection.cs
ImperatorToCK3/Data_Files/configurables/converter_faiths.txt

Fix most of the converter's religions not having a pilgrimage doctrine

---

ImperatorToCK3/Data_Files/configurables/converter_cultures.txt
ImperatorToCK3/Data_Files/configurables/cultural_pillars/IRToCK3_language.txt
ImperatorToCK3/Data_Files/configurables/removable_file_blocks_wtwsms.txt
ImperatorToCK3/Data_Files/configurables/replaceable_file_blocks_wtwsms.txt
ImperatorToCK3/Outputter/FileTweaker.cs

Tweaks for conversion to WtWSMS version 0.1.6

---

ImperatorToCK3/Data_Files/blankMod/output/common/culture/creation_names/IRToCK3_names.liquid
ImperatorToCK3/Data_Files/blankMod/output/common/culture/creation_names/IRToCK3_names_hybrid.liquid
ImperatorToCK3/Data_Files/blankMod/output/localization/replace/english/zzz_IRToCK3_vanilla_override_l_english.yml
ImperatorToCK3/Data_Files/configurables/converter_cultures.txt
ImperatorToCK3/Data_Files/configurables/culture_map.txt
ImperatorToCK3/Data_Files/configurables/localization/base/english/CONVERTER_culture_creation_names_l_english.yml
ImperatorToCK3/Data_Files/configurables/localization/base/english/CONVERTER_cultures_l_english.yml

Added various creation names for Macedonian/Hellenistic cultures;
Added Roman + Cretan/Neo-Minoan creation name;
Added Roman + Anatolian creation name;
Added Kemetic + Arabic creation name for Egyptian;
Added Kemetic creation name for Coptic;
Added custom syro_hellenic (Syriac) Culture;
Renamed base game's Syriac (assyrian) culture to Assyrian;
Changed Imperator tayuan culture to map to sogdian;

Added Culture Creation Names, Cultures, and Mappings

---

ImperatorToCK3/CK3/Cultures/PillarCollection.cs
ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/Titles/Title.cs
ImperatorToCK3/CommonUtils/BufferedReaderExtensions.cs
ImperatorToCK3/Imperator/Religions/ReligionCollection.cs

Sentry event ID: d6fc38d7b2af4d46bcd0165313488fd6

Fix exception when loading heritage parameters

---

ImperatorToCK3/Data_Files/configurables/converter_faiths.txt

https://forum.paradoxplaza.com/forum/threads/imperator-to-ck3-release-thread.1415172/post-30179062

Fix error.log errors about missing localization for SunGodName

---

ImperatorToCK3/Outputter/CoatOfArmsOutputter.cs

https://forum.paradoxplaza.com/forum/threads/imperator-to-ck3-development-thread.1415175/post-30189749

Fix CK3 CoAs not being replaced by I:R ones

---

ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/World.cs

Fix religious heads having OTL lieges that don't make sense

---

ImperatorToCK3/Data_Files/configurables/removable_file_blocks_roa.txt

ROA changed its tributary files, so updated files with those changes

Update files for ROA 3.6.1 (1.15)

---

ImperatorToCK3/CK3/Cultures/CultureCollection.cs

Sentry event ID: 958d40c149c04f0ab4ddef241c7df5e7

Prevent an exception when determining the ancestors of a culture

---

ImperatorToCK3/Data_Files/configurables/government_map.txt

https://forum.paradoxplaza.com/forum/threads/imperator-to-ck3-release-thread.1415172/post-30267524

Prefer `administrative_government` over TFE's `imperial_government`

---

ImperatorToCK3.UnitTests/Mappers/TagTitle/TagTitleMapperTests.cs
ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/Titles/Title.cs
ImperatorToCK3/Mappers/TagTitle/TagTitleMapper.cs

Avoid localization key hash conflicts when generating CK3 title IDs

---

ImperatorToCK3/Data_Files/configurables/cultural_pillars/IRToCK3_heritage.txt
ImperatorToCK3/Data_Files/configurables/removable_file_blocks_wtwsms.txt

Compatch for WtWSMS 0.1.6.1

---

ImperatorToCK3/CK3/Diplomacy/DiplomacyDB.cs
ImperatorToCK3/Data_Files/configurables/religion_map.txt

Also fixes wrong log level in ImportImperatorLeagues.
closes #2640

Prefer Chalcedonian over Orthodox and Catholic for TFE and WtWSMS

---

ImperatorToCK3/Data_Files/blankMod/output/map_data/geographical_regions/zzz_IRToCK3_regions.txt.liquid
ImperatorToCK3/Data_Files/configurables/removable_file_blocks_roa.txt
ImperatorToCK3/Data_Files/configurables/replaceable_file_blocks_roa.txt

- Added new geographical_region liquid file to blank mod for any regions we need to add ourselves to specific mods.
- Updated for RoA 4.0.1

ROA Update

---

.github/workflows/ck3-tiger.conf
.github/workflows/integration_tests.yml
ImperatorToCK3/Data_Files/blankMod/output/common/named_colors/IRToCK3_culture_colors.txt.liquid

Add ck3-tiger validation to integration tests and fix some ck3-tiger warnings

---

ImperatorToCK3/CK3/World.cs
ImperatorToCK3/Configuration.cs
ImperatorToCK3/Data_Files/fronter_configuration/fronter-options.txt
ImperatorToCK3/Data_Files/fronter_configuration/options_l_english.yml
ImperatorToCK3/Data_Files/fronter_configuration/options_l_simp_chinese.yml

A frontend option to skip holding owners import

---

ImperatorToCK3/CK3/Characters/Character.cs

Sentry event ID: 9ecd1e270bb445c0afe42a4b8872a054

Fix exception due to concurrent collection update

---

ImperatorToCK3/CK3/Titles/LandedTitles.cs
ImperatorToCK3/CK3/Titles/Title.cs
ImperatorToCK3/CK3/World.cs

Should reduce the number of issues in CodeFactor.

Reduce the complexity of a few methods

---

.gitignore
ImperatorToCK3/Data_Files/configurables/removable_file_blocks_wtwsms.txt
ImperatorToCK3/Outputter/FileTweaker.cs
ImperatorToCK3/Outputter/WorldOutputter.cs

Update for WtWSMS 0.1.8
