ImperatorToCK3/Source/CK3/CK3World.cpp, ImperatorToCK3/Source/CK3/Titles/LandedTitles.cpp, ImperatorToCK3/Source/CK3/Titles/Title.cpp, ImperatorToCK3/Source/CK3/Titles/Title.h, ImperatorToCK3/Source/CK3/Titles/TitlesHistory.cpp, ImperatorToCK3/Source/Imperator/Characters/PortraitData.cpp, ImperatorToCK3/Source/Mappers/CoaMapper/CoaMapper.cpp, ImperatorToCK3/Source/Mappers/LocalizationMapper/LocalizationMapper.cpp
Also added an `addFoundTitle` static function to be used in both Title and LandedTitles to avoid duplication.
=> Used .at() instead of operator[] where possible

ImperatorToCK3/ImperatorToCK3.vcxproj, ImperatorToCK3/Source/Imperator/Characters/Character.h, ImperatorToCK3/Source/Imperator/Characters/CharacterFactory.cpp, ImperatorToCK3/Source/Imperator/Characters/CharacterFactory.h, ImperatorToCK3/Source/Imperator/Characters/Characters.cpp, ImperatorToCK3/Source/Imperator/Characters/Characters.h, ImperatorToCK3/Source/Imperator/Characters/PortraitData.cpp, ImperatorToCK3/Source/Imperator/Characters/PortraitData.h, ImperatorToCK3/Source/Imperator/ImperatorWorld.cpp, ImperatorToCK3Tests/ImperatorWorldTests/Characters/CharacterTests.cpp, ImperatorToCK3Tests/ImperatorWorldTests/Characters/CharactersTests.cpp, ImperatorToCK3Tests/ImperatorWorldTests/Characters/PortraitDataTests.cpp
`genes` and `endDate` neither need to nor should be stored in every Imperator Character. Used shared pointers instead.
=> Fixed a serious memory usage issue

ImperatorToCK3/Source/CK3/Province/CK3Province.cpp, ImperatorToCK3/Source/CK3/Province/CK3Province.h, ImperatorToCK3/Source/CK3/Province/ProvinceDetails.cpp, ImperatorToCK3/Source/CK3/Province/ProvinceDetails.h, ImperatorToCK3Tests/CK3WorldTests/Province/CK3ProvinceDetailsTests.cpp, ImperatorToCK3Tests/CK3WorldTests/Province/CK3ProvinceTests.cpp, ImperatorToCK3Tests/CK3WorldTests/Province/CK3ProvincesTests.cpp, ImperatorToCK3Tests/ImperatorToCK3Tests.vcxproj, ImperatorToCK3Tests/ImperatorToCK3Tests.vcxproj.filters, ImperatorToCK3Tests/ImperatorWorldTests/Countries/CountriesTests.cpp, ImperatorToCK3Tests/TestFiles/CK3ProvinceDetailsCorrect.txt
@Zemurin This should fix the issue with "unowned" CK3 provinces on rulers' death.
=> Used History to parse CK3 province details

ImperatorToCK3/ImperatorToCK3.vcxproj, ImperatorToCK3/ImperatorToCK3.vcxproj.filters, ImperatorToCK3/Source/CK3/CK3World.cpp, ImperatorToCK3/Source/CK3/CK3World.h, ImperatorToCK3/Source/CK3/Character/CK3Character.h, ImperatorToCK3/Source/CK3/Dynasties/Dynasty.cpp, ImperatorToCK3/Source/CK3/Dynasties/Dynasty.h, ImperatorToCK3/Source/CK3Outputter/CK3WorldOutputter.cpp, ImperatorToCK3/Source/CK3Outputter/outCharacter.cpp, ImperatorToCK3/Source/CK3Outputter/outCharacters.cpp, ImperatorToCK3/Source/CK3Outputter/outDynasties.cpp, ImperatorToCK3/Source/CK3Outputter/outDynasties.h, ImperatorToCK3/Source/CK3Outputter/outDynasty.cpp, ImperatorToCK3/Source/CK3Outputter/outDynasty.h, ImperatorToCK3/Source/CK3Outputter/outLocalization.cpp, ImperatorToCK3/Source/Imperator/Characters/Characters.cpp, ImperatorToCK3/Source/Imperator/Families/Family.cpp, ImperatorToCK3/Source/Imperator/Families/Family.h, ImperatorToCK3/Source/Imperator/Families/FamilyFactory.cpp, ImperatorToCK3/Source/Imperator/Families/FamilyFactory.h, ImperatorToCK3/Source/Imperator/ImperatorWorld.cpp, ImperatorToCK3/Source/Imperator/ImperatorWorld.h, ImperatorToCK3Tests/CK3WorldTests/Dynasties/DynastyTests.cpp, ImperatorToCK3Tests/ImperatorToCK3Tests.vcxproj, ImperatorToCK3Tests/ImperatorToCK3Tests.vcxproj.filters, ImperatorToCK3Tests/ImperatorWorldTests/Families/FamilyTests.cpp
Closes #55.
Tests are missing, but checked the results in-game.
=> Convert non-minor Imperator Families to CK3 Dynasties

ImperatorToCK3/Source/Imperator/Characters/Character.cpp, ImperatorToCK3/Source/Imperator/Characters/Character.h, ImperatorToCK3/Source/Imperator/Characters/CharacterAttributes.cpp, ImperatorToCK3/Source/Imperator/Characters/CharacterAttributes.h, ImperatorToCK3/Source/Imperator/Characters/CharacterFactory.cpp, ImperatorToCK3/Source/Imperator/Characters/CharacterFactory.h, ImperatorToCK3/Source/Imperator/Characters/CharacterName.cpp, ImperatorToCK3/Source/Imperator/Characters/CharacterName.h, ImperatorToCK3/Source/Imperator/Characters/Characters.cpp, ImperatorToCK3/Source/Imperator/Characters/Characters.h, ImperatorToCK3/Source/Imperator/Characters/PortraitData.cpp, ImperatorToCK3/Source/Imperator/Characters/PortraitData.h, ImperatorToCK3/Source/Imperator/Countries/Countries.cpp, ImperatorToCK3/Source/Imperator/Countries/Countries.h, ImperatorToCK3/Source/Imperator/Countries/Country.cpp, ImperatorToCK3/Source/Imperator/Countries/Country.h, ImperatorToCK3/Source/Imperator/Countries/CountryCurrencies.cpp, ImperatorToCK3/Source/Imperator/Countries/CountryCurrencies.h, ImperatorToCK3/Source/Imperator/Countries/CountryFactory.cpp, ImperatorToCK3/Source/Imperator/Countries/CountryFactory.h, ImperatorToCK3/Source/Imperator/Countries/CountryName.cpp, ImperatorToCK3/Source/Imperator/Countries/CountryName.h, ImperatorToCK3Tests/ImperatorWorldTests/Characters/CharacterTests.cpp, ImperatorToCK3Tests/ImperatorWorldTests/Characters/CharactersTests.cpp, ImperatorToCK3Tests/ImperatorWorldTests/Characters/PortraitDataTests.cpp
- Used forward declarations in header files instead of includes wherever possible (AppVeyor build are getting too long).
- Applied my preferred format of opening curly braces (on the same line).
- No functionality changes.
=> Minor refactoring: Imperator Characters and Countries

ImperatorToCK3/Source/CK3/Character/CK3Character.cpp, ImperatorToCK3/Source/Imperator/Characters/Character.cpp, ImperatorToCK3/Source/Imperator/Characters/Characters.cpp
If a character's family has no definition, character's `family.first` has correct ID, but `family.second` remains nullptr. I added a check for that in `getCulture()`.
=> Fix for Imperator::Character::getCulture() causing crashes

ImperatorToCK3/Source/CK3/Dynasties/Dynasty.cpp, ImperatorToCK3/Source/Imperator/Families/Families.cpp, ImperatorToCK3/Source/Imperator/Families/Families.h, ImperatorToCK3/Source/Imperator/Families/Family.cpp, ImperatorToCK3/Source/Imperator/Families/Family.h, ImperatorToCK3/Source/Imperator/ImperatorWorld.cpp
The converter didn't handle edge cases like characters changing family.
=> Fix for unlinked family members crashing conversion

ImperatorToCK3.UnitTests/Imperator/Characters/CharacterTests.cs, ImperatorToCK3.UnitTests/Imperator/Characters/CharactersTests.cs, ImperatorToCK3/CK3/Titles/Title.cs, ImperatorToCK3/CK3/World.cs, ImperatorToCK3/Imperator/Characters/Character.cs, ImperatorToCK3/Imperator/Characters/Characters.cs
`characters.StoredCharacters.Add(id, character)` is a bit ugly and allows a mismatch between character id and key in the dictionary.
`characters.Add(character)` is safer and prettier.
=> Better encapsulation for Imperator Characters class

ImperatorToCK3.UnitTests/CK3/Titles/LandedTitlesTests.cs, ImperatorToCK3/CK3/Characters/Characters.cs, ImperatorToCK3/CK3/Titles/LandedTitles.cs, ImperatorToCK3/CK3/Titles/Title.cs, ImperatorToCK3/CK3/World.cs, ImperatorToCK3/Mappers/Region/CK3RegionMapper.cs
By making LandedTitles itself a `Dictionary<string, Title>`, we alleviate the need for StoredTitles property.
=> Simplify LandedTitles code with clever inheritance

ImperatorToCK3/CK3/Provinces/Province.cs
Refined Imperator Territory -> CK3 Holding mapping (No more spamming non-Tribal realms with Tribal Holdings, also Metropolises with Forts are considered as Castle Holdings for Monarchies)
=> Refined Imperator Territory -> CK3 Holding mapping

ImperatorToCK3/CK3/Provinces/Province.cs, ImperatorToCK3/Imperator/Provinces/Provinces.cs
It's fine if an Imperator provinces has no owner, this happens when it's uncolonised or impassable.
=> Fix Imperator provinces without owners being logged

ImperatorToCK3/Outputter/SuccessionTriggersOutputter.cs
Naming the file same as vanilla one did cause missing trigger errors in error.log.
=> Rename succession triggers file

ImperatorToCK3.UnitTests/CK3/Titles/LandedTitlesTests.cs, ImperatorToCK3/CK3/Titles/LandedTitles.cs, ImperatorToCK3/CK3/World.cs
CK3 development is converted from Imperator civilisation value (1 civ value = 1 dev level).
When an Imperator province is mapped to multiple CK3 provinces, its civ value is split between them.
For every county I sum the calculated development from provinces, then divide by the number of provinces. Then subtract a square root of that.
Development for counties outside of Imperator map is kept from vanilla.
=> Development conversion

ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs, ImperatorToCK3.UnitTests/Imperator/Countries/CountryTests.cs, ImperatorToCK3.UnitTests/Mappers/Culture/CultureMapperTests.cs, ImperatorToCK3/CK3/Characters/Character.cs, ImperatorToCK3/CK3/Provinces/Province.cs, ImperatorToCK3/Data_Files/configurables/culture_map.txt, ImperatorToCK3/Imperator/Countries/Country.cs, ImperatorToCK3/Imperator/Countries/CountryCollection.cs, ImperatorToCK3/Imperator/Countries/CountryFactory.cs, ImperatorToCK3/Imperator/World.cs, ImperatorToCK3/Mappers/Culture/CultureMapper.cs, ImperatorToCK3/Mappers/Culture/CultureMappingRule.cs
This allows us to make more detailed mappings. For example, Langobards have no separate culture in Imperator, but we are now able to use LGB (Langobardia) tag to make a mapping for them, instead of using a regional mapping.
=> Replace CK3 owner with Imperator historical tag in CultureMapper

ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs, ImperatorToCK3.UnitTests/CK3/Characters/TraitTests.cs, ImperatorToCK3.UnitTests/CK3/Dynasties/DynastyTests.cs, ImperatorToCK3.UnitTests/Mappers/Trait/TraitMapperTests.cs, ImperatorToCK3.UnitTests/TestFiles/CK3/game/common/traits/test_traits.txt, ImperatorToCK3.UnitTests/TestFiles/TraitMapperTests/trait_map_mapping_with_no_ck3.txt, ImperatorToCK3.UnitTests/TestFiles/TraitMapperTests/trait_map_multiple_ck3_in_rule.txt, ImperatorToCK3.UnitTests/TestFiles/TraitMapperTests/trait_map_undefined_ck3_trait.txt, ImperatorToCK3.UnitTests/TestFiles/configurables/trait_map.txt, ImperatorToCK3/CK3/Characters/Character.cs, ImperatorToCK3/CK3/Characters/Trait.cs, ImperatorToCK3/CK3/World.cs, ImperatorToCK3/Mappers/Trait/TraitMapper.cs
Prevents characters from having for example both `cynical` and `zealous` traits.
Should slightly improve CK3 load time #677.
=> Prevent opposite traits in characters from Imperator

ImperatorToCK3/CK3/Titles/LandedTitles.cs, ImperatorToCK3/CK3/Titles/Title.cs, ImperatorToCK3/CK3/World.cs, ImperatorToCK3/Imperator/World.cs
It's now possible for a holding owner to be converted to a count. Previously only barons were possible.
=> Convert more holding owners to title holders

ImperatorToCK3/CK3/Titles/LandedTitles.cs
closes #1310 
Before:
Noticeable oddities:
- Assyria
- Myos Hormos
After:
=> Don't convert holdings that belong to dukes or above

ImperatorToCK3/CK3/Titles/Title.cs
=> Log warning instead of throwing an exception on incorrect capital county ID

ImperatorToCK3/Data_Files/configurables/culture_map.txt
Culture changes that are primarily related to TFE conversions with two exceptions. Mostly based on "[Tweaks for conversion to Fallen Eagle](https://github.com/ParadoxGameConverters/ImperatorToCK3/issues/1467)" issue. Changes are:
- Punic, Old Egyptian, Slavic, and Hunnic convert to their TFE equivalents
- Dnieper Baltic and Slavic cultures are mapped to closest equivalent Invictus Balto-Slavic culture
- South Arabic and Himyarite are mapped to the Invictus South Levantine culture group
- Callaecian, Cantabrian and Asturian celtiberian cultures are mapped individually as they have TFE equivalents 
- TFE Noric and Illyrian represent their respective culture groups
- More germanic tag cultures along with fixing ones that would previously never work
- Change Tyrrenic mapping so Rhaetian could …
=> Culture tweaks for conversion to Fallen Eagle

ImperatorToCK3/CK3/Characters/DNAFactory.cs
Sentry event: 1fdcde106f2748f985c207620c48f9f7
=> Fix exception when no accessory gene template is found for object

ImperatorToCK3/Imperator/Characters/PortraitData.cs
Sentry event: d7000a22c8974f3993523b34db30aa2b
=> Temporary fix for broken Invictus DNA strings

ImperatorToCK3/CK3/Provinces/ProvinceCollection.cs
Sentry event ID: 4ae7df9d0cc0423184c1b132a5583ed2
=> Prevent exception when history/province_mapping contains wrong target

ImperatorToCK3/CK3/Titles/LandedTitles.cs
Previously, the development calculated for a CK3 province was an average of the civilisation values from corresponding Imperator provinces. Now it's a sum.
=> Change the way CK3 development from I:R is calculated

ImperatorToCK3/CK3/Dynasties/DynastyCollection.cs
Sentry event ID: 5b7c3fa1f24347759465e37505fb4f73
=> Prevent exception when converting same I:R family again

ImperatorToCK3/CK3/Dynasties/HouseCollection.cs
Sentry event ID: ace81263d6e2427582c49a054e630d4c
=> Fix exception while loading dynasty houses from CK3

.github/workflows/create_release.yml
Everyone should use the installer.
=> Release workflow: don't upload the release zip for Windows

ImperatorToCK3.sln.DotSettings, ImperatorToCK3/Outputter/OnActionOutputter.cs
=> TFE: prevent Chalcedonian being convertible to Nicene after 451.8.25

ImperatorToCK3/CK3/Titles/LandedTitles.cs, ImperatorToCK3/CK3/Titles/Title.cs
- destroy_on_succession
- can_destroy
- ignore_titularity_for_title_weighting
=> Add support for 3 more keywords in landed title definitions

ImperatorToCK3.UnitTests/Imperator/Jobs/JobsTests.cs, ImperatorToCK3.sln.DotSettings, ImperatorToCK3/CK3/Religions/Faith.cs, ImperatorToCK3/CK3/Religions/ReligionCollection.cs, ImperatorToCK3/CK3/Titles/LandedTitles.cs, ImperatorToCK3/CK3/Titles/Title.cs, ImperatorToCK3/CK3/World.cs, ImperatorToCK3/Imperator/Jobs/JobsDB.cs, ImperatorToCK3/Imperator/Jobs/OfficeJob.cs, ImperatorToCK3/Imperator/World.cs
The program now converts Imperator government officials to court chaplains, chancellors, stewards, marshals, bodyguards, court physicians, court tutors and chroniclers.
closes #89
=> Government office conversion

ImperatorToCK3/CK3/Dynasties/DynastyCollection.cs
Sentry event ID: e8422b6133144fa78a9047b602794072
=> Prevent exception while creating dynasties when a converter-generated mod is selected as one of the CK3 mods

ImperatorToCK3/CommonUtils/FileHelper.cs, ImperatorToCK3/Helpers/RakalyCaller.cs, ImperatorToCK3/Imperator/World.cs, ImperatorToCK3/Outputter/BookmarkOutputter.cs, ImperatorToCK3/Outputter/CharactersOutputter.cs, ImperatorToCK3/Outputter/CulturesOutputter.cs, ImperatorToCK3/Outputter/DynastiesOutputter.cs, ImperatorToCK3/Outputter/LocalizationOutputter.cs, ImperatorToCK3/Outputter/MenAtArmsOutputter.cs, ImperatorToCK3/Outputter/NamedColorsOutputter.cs, ImperatorToCK3/Outputter/OnActionOutputter.cs, ImperatorToCK3/Outputter/PillarOutputter.cs, ImperatorToCK3/Outputter/ProvincesOutputter.cs, ImperatorToCK3/Outputter/ReligionsOutputter.cs, ImperatorToCK3/Outputter/SuccessionTriggersOutputter.cs, ImperatorToCK3/Outputter/TitlesOutputter.cs, ImperatorToCK3/Outputter/WarsOutputter.cs, ImperatorToCK3/Outputter/WorldOutputter.cs
Sentry event ID: 24c5422a16cb4914ab7fa99143ff62c5
=> Make multiple attempts to remove the temporary melted save file if it's used by another process

ImperatorToCK3/Exceptions/ConverterException.cs, ImperatorToCK3/Exceptions/UserErrorException.cs
Not needed in the code for now, but fixes warnings.
=> Implement standard constructors for UserErrorException and ConverterException

ImperatorToCK3/CK3/World.cs
Sentry event ID: b600839a66f24f06a6e837a16e27efb2
=> Fix exception when christianity_religion is not found in CK3

ImperatorToCK3/CK3/CK3LocDB.cs
https://forum.paradoxplaza.com/forum/threads/imperator-to-ck3-release-thread.1415172/post-29857505
=> Fix featured bookmark character having no localization

ImperatorToCK3.UnitTests/Imperator/Countries/CountryNameTests.cs, ImperatorToCK3/CK3/Titles/LandedTitles.cs, ImperatorToCK3/CK3/Titles/Title.cs, ImperatorToCK3/Imperator/Countries/CountryName.cs, ImperatorToCK3/ImperatorToCK3.csproj
=> Fix some titles being localized as "[GetCountry('MRY').Custom('get_mry_adj')] Revolt" or "[GetCountry('PRY').Custom('get_pry_adj')] Revolt"

ImperatorToCK3.UnitTests/Imperator/Countries/CountryNameTests.cs, ImperatorToCK3/Imperator/Countries/CountryName.cs
Example:
```
country_name={
name="CIVILWAR_FACTION_NAME"
adjective="CIVILWAR_FACTION_ADJECTIVE"
base={
name="Tamilakam"
}
}
```
=> Fix revolt localization when an unlocalized name is used as base

ImperatorToCK3/CK3/Cultures/CultureCollection.cs
This avoids validating a culture twice if it's defined in two or more places. Should also reduce the number of warnings, if the first occurrence is from vanilla, and the following ones are added by mods to modify it.
=> Optimize the loading of CK3 cultures

ImperatorToCK3/Configuration.cs
Sentry event ID: 92f7299db51a4442bbf9b1a00783fc5c
=> Verify the entered CK3 mods path after reading the configuration

.gitignore, ImperatorToCK3/Data_Files/blankMod/output/common/decisions/zz_vanilla_decisions_override.txt
Credits to tanner918.
closes #2387
=> Prevent the Bosporan Kingdom formation through decision if it has a holder or de jure land

ImperatorToCK3/CK3/Characters/CharacterCollection.cs
Report:
https://forum.paradoxplaza.com/forum/threads/imperator-to-ck3-development-thread.1415175/post-30103921
https://forum.paradoxplaza.com/forum/threads/imperator-to-ck3-development-thread.1415175/post-30104168
=> Handle DNA generation exceptions

ImperatorToCK3/Data_Files/configurables/converter_faiths.txt
In the doctrines I set the head of faith to no head as it is more historically accurate than the Magi, everything else fits the mazdayasna with specific changes (issue #2401).
=> Add mithra_religion

ImperatorToCK3/Data_Files/configurables/converter_faiths.txt, ImperatorToCK3/Data_Files/configurables/localization/base/english/CONVERTER_religions_l_english.yml, ImperatorToCK3/Data_Files/configurables/religion_map.txt, ImperatorToCK3/Data_Files/configurables/replaceable_holy_sites.txt, ImperatorToCK3/Data_Files/converter_globals/ReadMe.txt, README.md
=> Map Invictus mithra_religion to converter's mithra_religion

ImperatorToCK3/CK3/Titles/LandedTitles.cs
Fixes the problem found in AEP, which as of version 0.8.2 has 2 duchies with invalid capitals.
=> Fix the logic for handling invalid duchy capitals

ImperatorToCK3/Imperator/World.cs
Sentry event ID: 3d5e4626986c4d0b8959e2ce3d21adc9
=> Treat an empty save as a user error

ImperatorToCK3.UnitTests/Mappers/Coa/CoaMapperTests.cs, ImperatorToCK3/CK3/Titles/Title.cs, ImperatorToCK3/Mappers/CoA/CoaMapper.cs
=> Don't warn about undefined CoA when dynamic CoA extraction is skipped

ImperatorToCK3/Imperator/Provinces/ProvinceCollection.cs
Related to failed job: https://github.com/ParadoxGameConverters/ImperatorToCK3/actions/runs/15014403802/job/42188997075
=> Fix exception when determining the "ownership" of an I:R impassable

ImperatorToCK3.iss
https://jrsoftware.org/ishelp/index.php?topic=archidentifiers
=> Allow the installer to run on Arm64-based Windows 11 via emulation

ImperatorToCK3.UnitTests/CK3/Cultures/CultureCollectionTests.cs, ImperatorToCK3/CK3/Cultures/CultureCollection.cs
Sentry event ID: 0ebe38c3b4b044eba5ab8406481e650f
=> Fix for stack overflow when checking for circular culture parents

ImperatorToCK3/CK3/World.cs, ImperatorToCK3/Configuration.cs, ImperatorToCK3/Data_Files/configurables/converter_cultures.txt, ImperatorToCK3/Data_Files/configurables/cultural_pillars/IRToCK3_heritage.txt, ImperatorToCK3/Data_Files/configurables/inventions_to_innovations_map.liquid, ImperatorToCK3/Data_Files/configurables/province_mappings/terra_indomita_to_aep.txt, ImperatorToCK3/Data_Files/configurables/removable_file_blocks_aep.txt, ImperatorToCK3/Data_Files/configurables/replaceable_file_blocks_aep.txt, ImperatorToCK3/Data_Files/configurables/succession_law_map.liquid, ImperatorToCK3/Data_Files/converter_globals/FAQ.txt, ImperatorToCK3/Outputter/BookmarkOutputter.cs, ImperatorToCK3/Outputter/FileTweaker.cs
AEP has been updated for CK3 1.16.
https://steamcommunity.com/workshop/filedetails/?id=2970440958
=> Restore support for the Asia Expansion Project mod

ImperatorToCK3/CK3/Cultures/CultureCollection.cs
The problem has been fixed in TFE for the next version.
=> Remove obsolete special fix for the `hunnic` culture in TFE

ImperatorToCK3/CK3/Dynasties/Dynasty.cs, ImperatorToCK3/CommonUtils/BufferedReaderExtensions.cs, ImperatorToCK3/Imperator/Armies/Subunit.cs, ImperatorToCK3/Imperator/Characters/Character.cs, ImperatorToCK3/Imperator/Countries/CountryFactory.cs, ImperatorToCK3/Imperator/Countries/RulerTerm.cs, ImperatorToCK3/Imperator/Families/Family.cs, ImperatorToCK3/Imperator/Pops/Pop.cs, ImperatorToCK3/Imperator/Provinces/ProvinceFactory.cs
Shout out to JetBrains dotMemory for finding string duplicates in the converter's memory.
=> Memory usage optimizations

.github/config/changelog-config.json, ImperatorToCK3/Outputter/ProvincesOutputter.cs
Fixes Rider's complaining about "Captured variable is disposed in outer scope".
Hopefully also fixes Sentry event 20a029d390f146a4baebe76f504024a7.
=> Tweaks to the province outputting code

ImperatorToCK3/ImperatorToCK3.csproj
Set CETCompat to false in ImperatorToCK3.csproj to address compatibility concerns as referenced in issue #2638.
closes #2638
=> Disable CETCompat in project settings

ImperatorToCK3.UnitTests/ConfigurationTests.cs, ImperatorToCK3/Configuration.cs
Introduced validation in Configuration to throw UserErrorException when unsupported mod combinations are detected. Added unit tests to verify exceptions are thrown for specific mod pairs.
Sentry event ID: 0e82de74ff304d16bd8277e049a4f1a6
=> Add checks for unsupported CK3 mod combinations

ImperatorToCK3.UnitTests/ConfigurationTests.cs, ImperatorToCK3/Configuration.cs
Added logic to verify that CK3ModsPath points to the standard Crusader Kings III mods directory, including handling trailing separators and platform-specific path comparisons. Introduced unit tests to ensure correct validation and error handling for both valid and invalid paths.
Sentry event ID: 2bfcd84eccba4d66ba420aba627f2d05
=> Improve the verification of CK3 Mod Directory
